### PR TITLE
Add enhanchment data in the xrimage attributes

### PR DESCRIPTION
**Pull request by vgiuffrida**
Satpy enhancement data is necessary in ninjotiff writer to calculate proper image data values and scale and offset metadata. 
Following feature is used to store enhancement data in the xrimage attributes in order to have them available in writer:

Add a set_outputinfo function used to store output data in xrimage attributes.

Add crude stretch values to the xrimage attributes.

 - [x] Tests added (for all bug fixes or enhancements)
 - [x] Tests passed (for all non-documentation changes)
 - [X] Passes ``git diff origin/master **/*py | flake8 --diff`` (remove if you did not edit any Python files)

### CODE REVIEW

**Comment by djhoese** [comment]
Is there any significance of `outputinfo`? Should it maybe be `output_info` to be more pythonic?

**Comment by vgiuffrida** [comment]
> Is there any significance to the `outputinfo` name? Should it maybe be `output_info` to be more pythonic?

I chose `outputinfo` because it stores information about the satpy output object.
Of course I can change it to `output_info` or any other appropriate name

**Comment by djhoese** [comment]
Ok, I wasn't sure if it meant something to some older software or something else. I personally would like `set_output_info` instead of `set_outputinfo`. Is the change in `crude_stretch` needed? If not, then couldn't this be all done inside Satpy by modifying the `img.data.attrs` directly?

If it is needed, then shouldn't `crude_stretch` be calling `set_output_info` instead of replicating the functionality?

`if len(outputinfo_data) > 0` could also be changed to `if output_info` to simplify the logic.

I didn't talk to you guys much at the PCW so I'm open to discussion if this is something that @mraspaud suggested or if I'm missing something.

**Comment by vgiuffrida** [comment]
> Ok, I wasn't sure if it meant something to some older software or something else. I personally would like `set_output_info` instead of `set_outputinfo`. Is the change in `crude_stretch` needed? If not, then couldn't this be all done inside Satpy by modifying the `img.data.attrs` directly?

I am using the `set_output_info` as an additional satpy enhancement operation to save some data.
Stretch values are passed, instead, to the stretch function.

So I think I could do everythig in satpy if I replicate stretch values in the `set_output_info` kwargs configuration.
It would be maybe redundant and also I could give wrong stretch values to the output_info, different from the real stretch values used on the image operation.

But let me know if you have any preferences

> If it is needed, then shouldn't `crude_stretch` be calling `set_output_info` instead of replicating the functionality?
> 

If left in `crude_stretch`: you're right, calling `set_output_info` from `crude_stretch` would be better.

**Comment by djhoese** [comment]
In the past for NinJo I think we've always left the stretching to the NinJo writer and not enhanced it otherwise. So this idea implemented here is new to me and I'm trying to wrap my head around the need for it.

I agree that it would require repeating min/max values in the enhancement configuration, but it also provides more flexibility. It makes the added metadata an "opt-in" feature per-user.

Just brainstorming: I think the long term solution would require us to manage metadata for DataArrays better than we are already. @sfinkens has similar issues in Satpy with satellite position metadata which *should* be standard for all satellite-based data. Similarly, a history of what was done to the data (what enhancement operations were applied) should be kept with the DataArray. Both of these things should be available with out polluting the "original" metadata of the DataArray.

**Comment by mraspaud** [comment]
I'm closing this as I believe we solved it (although a bit differently) in #55 . Feel free to reopen if you feel like this should still be addressed.

**Pull request closed without merging**
