### PR TITLE
Update colorbrew colormaps to be more accurate

### PR DESCRIPTION
**Pull request by djhoese**
While working on other pull requests @mraspaud and I noticed that some colormaps have artifacts from color interpolation. This seems to mostly be caused by the colormaps (taken from colorbrewer2.org) only being defined by two colors when they could be defined by 3 or more (sometimes 12) colors. This PR adds a helper script for loading the JSON version of the colorbrewer colormaps and generated the necessary Python code to be copied to colormap.py.

 - [ ] Closes #xxxx (remove if there is no corresponding issue, which should only be the case for minor changes)
 - [ ] Tests added (for all bug fixes or enhancements)
 - [ ] Tests passed (for all non-documentation changes)
 - [ ] Passes ``git diff origin/master **/*py | flake8 --diff`` (remove if you did not edit any Python files)
 - [ ] Fully documented (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)

### CODE REVIEW

**Comment by djhoese** [comment]
Note: I know the helper script needs refactoring.

**Comment by djhoese** [comment]
Eh I don't know how to feel about these results. Even `greys` doesn't have `128 / 255` in the middle of the colormap. That's just how colorbrewer is. I don't think it is wrong, but it is way different than what we used to have.

**Comment by mraspaud** [comment]
I for one like the updated colourmaps much better! The sequential ones in particular are much more vibrant.

**Review by mraspaud — APPROVED** [review]
LGTM!

**Comment by mraspaud** [comment]
codefactor is not happy about the new function though...

**Comment by djhoese** [comment]
I refactored the code quite a bit. Much cleaner and less complex now (even checked with `python -m mccabe`). I'll merge this now and then I'd like to work on adding more pre-commit checks. I manually ran mypy on my new script in this PR to make sure types were valid, but I'd like to throw black in the mix too.

**Pull request merged**
